security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

        clients:
            entity:
                class: App\Entity\Client
                property: xAuthToken

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/(?!api)
            lazy: true
            jwt: ~
            stateless: false
            provider: app_user_provider
            custom_authenticators:
                - App\Security\ApiAuthenticator
            remember_me: 
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

            logout:
                path: /logout
                target: /
        api:
            pattern: ^/api
            stateless: true
            provider: clients
            custom_authenticators:
                - App\Security\ApiAuthenticator
                - App\Security\JwtUserAuthenticator


    access_control:
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:

            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon